In [136]:
import pandas as pd
import numpy as np
import pyodbc

In [137]:
conn = pyodbc.connect('DSN=WINPASS_SATEC_RO_64;')

In [138]:
sql1 = "select * from table_cg1"

In [139]:
df = pd.read_sql_query(sql=sql1, con=conn)

In [141]:
df.columns

Index(['f_NCONTRAT', 'CONTRAT', 'NC', 'REF_CGAIM', 'LCGAIM', 'AGENCE',
       'AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1',
       'CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',
       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2',
       'COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8',
       'COUTTX9', 'GARANTIE', 'GARANTIEG', 'FRAIS', 'PRIME', 'HT', 'TTC',
       'PRIMEG', 'TTCG', 'COM', 'ligq_commission', 'DTSITUATION', 'DOMAGIS_ON',
       'DTRECOUVREMENT', 'MOUVEMENT', 'STATUT', 'TXCOM'],
      dtype='object')

In [142]:
df1_ttc = df.pivot_table(index=['CONTRAT', 'NC', 'COM','ligq_commission'],
                             columns =['GARANTIE'], 
                             values =['TTCG']).reset_index().fillna(0).rename(columns={'G01':'G01ttc','G02':'G02ttc','G03':'G03ttc','G04':'G04ttc','G05':'G05ttc','G06':'G06ttc',
                                                                                      'G07':'G07ttc','G08':'G08ttc','GFG':'GFGttc','SIN':'SINttc'});df1_ttc

         CONTRAT NC     COM ligq_commission     TTCG                         \
GARANTIE                                      G01ttc  G02ttc  G03ttc G04ttc
0          10778  2  249.37          439.41  1477.94  369.48  164.21  41.05
1          10778  3  353.29          637.82  2145.25  536.31  238.36  59.59
2          10778  4  117.57          187.80   631.66  157.92   70.19  17.55
3          10778  5  117.57          187.80   631.66  157.92   70.19  17.55
4          10778  6  117.57          187.80   631.66  157.92   70.19  17.55
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2222.19  555.56  246.91  61.73
6580        8753  8  199.38          343.98  1156.94  289.23  128.55  32.14
6581        8753  9  199.38          343.98  1156.94  289.23  128.55  32.14
6582        8868  1  212.46          418.74  2131.43  710.48  236.84  78.94
6583        9191  1  198.37          342.05  1150.45  287.61  127.82  31.96


GARANTIE  G05ttc  G06ttc G07ttc G08ttc GFGttc SINttc
0         100.27  114.04  12.11    5.9   48.0    0.0
1         145.54  165.53  17.58    5.9   48.0    0.0
2          42.86   48.74   5.18    5.9   48.0    0.0
3          42.86   48.74   5.18    5.9   48.0    0.0
4          42.86   48.74   5.18    5.9   48.0    0.0
...          ...     ...    ...    ...    ...    ...
6579      150.76  171.47  18.20    5.9   48.0    0.0
6580       78.49   89.27   9.48    5.9   48.0    0.0
6581       78.49   89.27   9.48    5.9   48.0    0.0
6582      156.64  175.42  18.79    3.3   48.0    0.0
6583       78.05   88.78   9.43    5.9   48.0    0.0

[6584 rows x 14 columns]

In [143]:
df1_ht = df.pivot_table(index=['CONTRAT', 'NC',  'COM', 'ligq_commission'],                             
                             columns =['GARANTIE'], 
                             values =['PRIMEG']).reset_index().fillna(0).rename(columns={'G01':'G01ht','G02':'G02ht','G03':'G03ht','G04':'G04ht',
                             'G05':'G05ht','G06':'G06ht','G07':'G07ht','G08':'G08ht','GFG':'GFGht','SIN':'SINht'});df1_ht

         CONTRAT NC     COM ligq_commission   PRIMEG                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32


GARANTIE   G05ht   G06ht  G07ht G08ht GFGht SINht
0          93.41  104.62  11.21   5.9  48.0   0.0
1         135.59  151.86  16.27   5.9  48.0   0.0
2          39.93   44.72   4.79   5.9  48.0   0.0
3          39.93   44.72   4.79   5.9  48.0   0.0
4          39.93   44.72   4.79   5.9  48.0   0.0
...          ...     ...    ...   ...   ...   ...
6579      140.45  157.31  16.85   5.9  48.0   0.0
6580       73.12   81.90   8.77   5.9  48.0   0.0
6581       73.12   81.90   8.77   5.9  48.0   0.0
6582      145.93  160.94  17.24   3.3  48.0   0.0
6583       72.71   81.45   8.73   5.9  48.0   0.0

[6584 rows x 14 columns]

In [144]:
df1_infos= df[['f_NCONTRAT', 'CONTRAT', 'NC','COM', 'ligq_commission', 'REF_CGAIM', 'LCGAIM', 'AGENCE','AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1','CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2','COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8','COUTTX9',  'DTSITUATION', 'DOMAGIS_ON','DTRECOUVREMENT',  'MOUVEMENT', 'STATUT', 'TXCOM']]

In [145]:
df1_infos.drop_duplicates().reset_index()

,index,f_NCONTRAT,CONTRAT,NC,COM,ligq_commission,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,0,10778/2,10778,2,249.37,439.41,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10,10778/3,10778,3,353.29,637.82,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,20,10778/4,10778,4,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,29,10778/5,10778,5,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,38,10778/6,10778,6,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,59894,8753/7,8753,7,365.28,660.69,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,59904,8753/8,8753,8,199.38,343.98,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,59914,8753/9,8753,9,199.38,343.98,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,59924,8868/1,8868,1,212.46,418.74,100482,100482,A G ENCE STRASBOURG IMMOBILIERE,Le Mathis,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,59933,9191/1,9191,1,198.37,342.05,None,None,IMMOBILIERE LORI,26 avenue Gabriel PÃ©ri,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [146]:
df2 =  df1_ht.merge( df1_ttc, on=['CONTRAT', 'NC',  'COM', 'ligq_commission']);df2

D:\anaconda\lib\site-packages\pandas\core\generic.py:3936: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

         CONTRAT NC     COM ligq_commission   PRIMEG                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...     TTCG                                         \
GARANTIE   G05ht   G06ht  ...   G01ttc  G02ttc  G03ttc G04ttc  G05ttc  G06ttc
0          93.41  104.62  ...  1477.94  369.48  164.21  41.05  100.27  114.04
1         135.59  151.86  ...  2145.25  536.31  238.36  59.59  145.54  165.53
2          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
3          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
4          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
...          ...     ...  ...      ...     ...     ...    ...     ...     ...
6579      140.45  157.31  ...  2222.19  555.56  246.91  61.73  150.76  171.47
6580       73.12   81.90  ...  1156.94  289.23  128.55  32.14   78.49   89.27
6581       73.12   81.90  ...  1156.94  289.23  128.55  32.14   78.49   89.27
6582      145.93  160.94  ...  2131.43  710.48  236.84  78.94  156.64  175.42
6583       72.71   81.45  ...  1150.45  287.61  127.82  31.96   78.05   88.78


GARANTIE G07ttc G08ttc GFGttc SINttc
0         12.11    5.9   48.0    0.0
1         17.58    5.9   48.0    0.0
2          5.18    5.9   48.0    0.0
3          5.18    5.9   48.0    0.0
4          5.18    5.9   48.0    0.0
...         ...    ...    ...    ...
6579      18.20    5.9   48.0    0.0
6580       9.48    5.9   48.0    0.0
6581       9.48    5.9   48.0    0.0
6582      18.79    3.3   48.0    0.0
6583       9.43    5.9   48.0    0.0

[6584 rows x 24 columns]

In [147]:
df2_infos=df1_infos.drop_duplicates().reset_index();df2_infos

,index,f_NCONTRAT,CONTRAT,NC,COM,ligq_commission,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,0,10778/2,10778,2,249.37,439.41,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10,10778/3,10778,3,353.29,637.82,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,20,10778/4,10778,4,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,29,10778/5,10778,5,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,38,10778/6,10778,6,117.57,187.80,27039,27039,AGENCE DU CAP,Avenue de la JetÃ©e,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,59894,8753/7,8753,7,365.28,660.69,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,59904,8753/8,8753,8,199.38,343.98,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,59914,8753/9,8753,9,199.38,343.98,25 772,25 772,BILAN PATRIMOINE,RÃ©sidence l' Alcyone,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,59924,8868/1,8868,1,212.46,418.74,100482,100482,A G ENCE STRASBOURG IMMOBILIERE,Le Mathis,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,59933,9191/1,9191,1,198.37,342.05,None,None,IMMOBILIERE LORI,26 avenue Gabriel PÃ©ri,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [148]:
df3=df2.merge(df2_infos, on=['CONTRAT', 'NC',  'COM', 'ligq_commission']);df3

D:\anaconda\lib\site-packages\pandas\core\reshape\merge.py:618: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)

,CONTRAT,NC,COM,ligq_commission,"(CONTRAT, )","(NC, )","(COM, )","(ligq_commission, )","(PRIMEG, G01ht)","(PRIMEG, G02ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778,2,249.37,439.41,10778,2,249.37,439.41,1355.91,338.97,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778,3,353.29,637.82,10778,3,353.29,637.82,1968.12,492.03,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,10778,4,117.57,187.80,10778,4,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,10778,5,117.57,187.80,10778,5,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,10778,6,117.57,187.80,10778,6,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,8753,7,365.28,660.69,8753,7,365.28,660.69,2038.71,509.69,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,8753,8,199.38,343.98,8753,8,199.38,343.98,1061.41,265.35,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,8753,9,199.38,343.98,8753,9,199.38,343.98,1061.41,265.35,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,8868,1,212.46,418.74,8868,1,212.46,418.74,1955.44,651.82,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,9191,1,198.37,342.05,9191,1,198.37,342.05,1055.46,263.86,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [155]:
df3.drop(df3.columns[[4]], axis=1, inplace=True);

In [156]:
df3

,CONTRAT,NC,COM,ligq_commission,"(PRIMEG, G01ht)","(PRIMEG, G02ht)","(PRIMEG, G03ht)","(PRIMEG, G04ht)","(PRIMEG, G05ht)","(PRIMEG, G06ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778,2,249.37,439.41,1355.91,338.97,150.65,37.66,93.41,104.62,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778,3,353.29,637.82,1968.12,492.03,218.68,54.67,135.59,151.86,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,10778,4,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,10778,5,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,10778,6,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,8753,7,365.28,660.69,2038.71,509.69,226.52,56.63,140.45,157.31,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,8753,8,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,8753,9,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,8868,1,212.46,418.74,1955.44,651.82,217.28,72.42,145.93,160.94,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,9191,1,198.37,342.05,1055.46,263.86,117.27,29.32,72.71,81.45,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [157]:
df3.to_csv("df5.csv",sep='\t')

In [158]:
df3.columns

Index([          'CONTRAT',                'NC',               'COM',
         'ligq_commission', ('PRIMEG', 'G01ht'), ('PRIMEG', 'G02ht'),
       ('PRIMEG', 'G03ht'), ('PRIMEG', 'G04ht'), ('PRIMEG', 'G05ht'),
       ('PRIMEG', 'G06ht'), ('PRIMEG', 'G07ht'), ('PRIMEG', 'G08ht'),
       ('PRIMEG', 'GFGht'), ('PRIMEG', 'SINht'),  ('TTCG', 'G01ttc'),
        ('TTCG', 'G02ttc'),  ('TTCG', 'G03ttc'),  ('TTCG', 'G04ttc'),
        ('TTCG', 'G05ttc'),  ('TTCG', 'G06ttc'),  ('TTCG', 'G07ttc'),
        ('TTCG', 'G08ttc'),  ('TTCG', 'GFGttc'),  ('TTCG', 'SINttc'),
                   'index',        'f_NCONTRAT',         'REF_CGAIM',
                  'LCGAIM',            'AGENCE',         'AGENCE_A1',
               'AGENCE_A2',         'AGENCE_CP',      'AGENCE_VILLE',
               'CHANTIER1',         'CHANTIER2',         'CHANTIER3',
              'CPCHANTIER',        'VILLECHANT',             'Debut',
                     'Fin',           'NATURE1',           'NATURE2',
                 'NATURE3',            'COUTTX',           'COUTTX1',
                 'COUTTX2',           'COUTTX3',           'COUTTX4',
                 'COUTTX5',           'COUTTX6',           'COUTTX7',
                 'COUTTX8',           'COUTTX9',       'DTSITUATION',
              'DOMAGIS_ON',    'DTRECOUVREMENT',         'MOUVEMENT',
                  'STATUT',             'TXCOM'],
      dtype='object')

In [160]:
df3[(df3['CONTRAT']=='11732')&(df3['NC']=='3') ]

,CONTRAT,NC,COM,ligq_commission,"(PRIMEG, G01ht)","(PRIMEG, G02ht)","(PRIMEG, G03ht)","(PRIMEG, G04ht)","(PRIMEG, G05ht)","(PRIMEG, G06ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
1659,11732,3,0.00,-131.16,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,2016-05-15,DOMAGIS,2016-11-02,1,Ajout,11.0
1660,11732,3,0.00,131.16,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,2016-05-15,DOMAGIS,2016-08-05,1,Ajout,11.0
1661,11732,3,81.98,131.16,0.00,0.00,0.00,0.00,0.00,0.00,...,NaN,NaN,NaN,NaN,2016-05-15,DOMAGIS,2016-11-02,1,Ajout,11.0
1662,11732,3,117.57,213.14,1062.37,265.59,118.04,29.51,73.19,81.97,...,NaN,NaN,NaN,NaN,2016-05-15,DOMAGIS,2016-04-29,1,Ajout,11.0