In [97]:
import pandas as pd
import numpy as np
import pyodbc

In [4]:
df = pd.DataFrame({'CONTRAT':['C1', 'C1','C1','C2','C2'], 
                   'GARANTIE':['G01', 'G02','G03','G01','G03'],
                   'HT':[10.0,11.0,12.0,21.0,22.0],
                   'TTC':[15.0,16.0,17.0,29.0,30.0]
                  });df

  CONTRAT GARANTIE    HT   TTC
0      C1      G01  10.0  15.0
1      C1      G02  11.0  16.0
2      C1      G03  12.0  17.0
3      C2      G01  21.0  29.0
4      C2      G03  22.0  30.0

In [98]:
conn = pyodbc.connect('DSN=WINPASS_SATEC_RO_64;')

In [6]:
sql1 = "select * from table_cg1  where CONTRAT in( '10778', '11244','10933', '11026','11296','11300','11323','11355','11357','11365') "

In [99]:
sql1 = "select * from table_cg1"

In [100]:
df = pd.read_sql_query(sql=sql1, con=conn)

In [101]:
df.columns

Index(['f_NCONTRAT', 'CONTRAT', 'NC', 'REF_CGAIM', 'LCGAIM', 'AGENCE',
       'AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1',
       'CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',
       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2',
       'COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8',
       'COUTTX9', 'GARANTIE', 'GARANTIEG', 'FRAIS', 'PRIME', 'HT', 'TTC',
       'PRIMEG', 'TTCG', 'COM', 'ligq_commission', 'DTSITUATION', 'DOMAGIS_ON',
       'DTRECOUVREMENT', 'MOUVEMENT', 'STATUT', 'TXCOM'],
      dtype='object')

In [105]:
df

,f_NCONTRAT,CONTRAT,NC,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,AGENCE_A2,AGENCE_CP,AGENCE_VILLE,...,PRIMEG,TTCG,COM,ligq_commission,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,1355.91,1477.94,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,338.97,369.48,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
2,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,150.65,164.21,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
3,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,37.66,41.05,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
4,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,93.41,100.27,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59937,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,72.71,78.05,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59938,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,81.45,88.78,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59939,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,8.73,9.43,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59940,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,5.90,5.90,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59941,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,48.00,48.00,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [107]:
df_long_ttc = df.pivot_table(index=['CONTRAT', 'NC', 'COM', 'ligq_commission'],
                             columns =['GARANTIE'], 
                             values =['TTC']).reset_index().fillna(0).rename(columns={'G01':'G01ttc','G02':'G02ttc','G03':'G03ttc','G04':'G04ttc',
                             'G05':'G05ttc','G06':'G06ttc','G07':'G07ttc','G08':'G08ttc','GFG':'GFGttc','SIN':'SINttc'});df_long_ttc

         CONTRAT NC     COM ligq_commission      TTC                         \
GARANTIE                                      G01ttc  G02ttc  G03ttc G04ttc
0          10778  2  249.37          439.41  1477.94  369.48  164.21  41.05
1          10778  3  353.29          637.82  2145.25  536.31  238.36  59.59
2          10778  4  117.57          187.80   631.66  157.92   70.19  17.55
3          10778  5  117.57          187.80   631.66  157.92   70.19  17.55
4          10778  6  117.57          187.80   631.66  157.92   70.19  17.55
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2222.19  555.56  246.91  61.73
6580        8753  8  199.38          343.98  1156.94  289.23  128.55  32.14
6581        8753  9  199.38          343.98  1156.94  289.23  128.55  32.14
6582        8868  1  212.46          418.74  2131.43  710.48  236.84  78.94
6583        9191  1  198.37          342.05  1150.45  287.61  127.82  31.96


GARANTIE  G05ttc  G06ttc G07ttc G08ttc GFGttc SINttc
0         100.27  114.04  12.11    5.9   48.0    0.0
1         145.54  165.53  17.58    5.9   48.0    0.0
2          42.86   48.74   5.18    5.9   48.0    0.0
3          42.86   48.74   5.18    5.9   48.0    0.0
4          42.86   48.74   5.18    5.9   48.0    0.0
...          ...     ...    ...    ...    ...    ...
6579      150.76  171.47  18.20    5.9   48.0    0.0
6580       78.49   89.27   9.48    5.9   48.0    0.0
6581       78.49   89.27   9.48    5.9   48.0    0.0
6582      156.64  175.42  18.79    3.3   48.0    0.0
6583       78.05   88.78   9.43    5.9   48.0    0.0

[6584 rows x 14 columns]

In [108]:
df_long_ht = df.pivot_table(index=['CONTRAT', 'NC',  'COM', 'ligq_commission'],                             
                             columns =['GARANTIE'], 
                             values =['HT']).reset_index().fillna(0).rename(columns={'G01':'G01ht','G02':'G02ht','G03':'G03ht','G04':'G04ht',
                             'G05':'G05ht','G06':'G06ht','G07':'G07ht','G08':'G08ht','GFG':'GFGht','SIN':'SINht'});df_long_ht

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32


GARANTIE   G05ht   G06ht  G07ht G08ht GFGht SINht
0          93.41  104.62  11.21   5.9  48.0   0.0
1         135.59  151.86  16.27   5.9  48.0   0.0
2          39.93   44.72   4.79   5.9  48.0   0.0
3          39.93   44.72   4.79   5.9  48.0   0.0
4          39.93   44.72   4.79   5.9  48.0   0.0
...          ...     ...    ...   ...   ...   ...
6579      140.45  157.31  16.85   5.9  48.0   0.0
6580       73.12   81.90   8.77   5.9  48.0   0.0
6581       73.12   81.90   8.77   5.9  48.0   0.0
6582      145.93  160.94  17.24   3.3  48.0   0.0
6583       72.71   81.45   8.73   5.9  48.0   0.0

[6584 rows x 14 columns]

In [109]:
new_df_pivot_all = df_long_ht.merge( df_long_ttc, on=['CONTRAT', 'NC',  'COM', 'ligq_commission']);new_df_pivot_all

D:\anaconda\lib\site-packages\pandas\core\generic.py:3936: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...      TTC                                         \
GARANTIE   G05ht   G06ht  ...   G01ttc  G02ttc  G03ttc G04ttc  G05ttc  G06ttc
0          93.41  104.62  ...  1477.94  369.48  164.21  41.05  100.27  114.04
1         135.59  151.86  ...  2145.25  536.31  238.36  59.59  145.54  165.53
2          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
3          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
4          39.93   44.72  ...   631.66  157.92   70.19  17.55   42.86   48.74
...          ...     ...  ...      ...     ...     ...    ...     ...     ...
6579      140.45  157.31  ...  2222.19  555.56  246.91  61.73  150.76  171.47
6580       73.12   81.90  ...  1156.94  289.23  128.55  32.14   78.49   89.27
6581       73.12   81.90  ...  1156.94  289.23  128.55  32.14   78.49   89.27
6582      145.93  160.94  ...  2131.43  710.48  236.84  78.94  156.64  175.42
6583       72.71   81.45  ...  1150.45  287.61  127.82  31.96   78.05   88.78


GARANTIE G07ttc G08ttc GFGttc SINttc
0         12.11    5.9   48.0    0.0
1         17.58    5.9   48.0    0.0
2          5.18    5.9   48.0    0.0
3          5.18    5.9   48.0    0.0
4          5.18    5.9   48.0    0.0
...         ...    ...    ...    ...
6579      18.20    5.9   48.0    0.0
6580       9.48    5.9   48.0    0.0
6581       9.48    5.9   48.0    0.0
6582      18.79    3.3   48.0    0.0
6583       9.43    5.9   48.0    0.0

[6584 rows x 24 columns]

In [110]:
new_df_pivot_all["totalht1"] = new_df_pivot_all[("HT","G01ht")]+new_df_pivot_all[("HT","G02ht")]+new_df_pivot_all[("HT","G03ht")] + new_df_pivot_all[("HT","G04ht")]+new_df_pivot_all[("HT","G05ht")]+new_df_pivot_all[("HT","G06ht")] +new_df_pivot_all[("HT","G07ht")]#+new_df_pivot_all[("HT","G08ht")]

In [111]:
new_df_pivot_all

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...     TTC                                        \
GARANTIE   G05ht   G06ht  ...  G02ttc  G03ttc G04ttc  G05ttc  G06ttc G07ttc
0          93.41  104.62  ...  369.48  164.21  41.05  100.27  114.04  12.11
1         135.59  151.86  ...  536.31  238.36  59.59  145.54  165.53  17.58
2          39.93   44.72  ...  157.92   70.19  17.55   42.86   48.74   5.18
3          39.93   44.72  ...  157.92   70.19  17.55   42.86   48.74   5.18
4          39.93   44.72  ...  157.92   70.19  17.55   42.86   48.74   5.18
...          ...     ...  ...     ...     ...    ...     ...     ...    ...
6579      140.45  157.31  ...  555.56  246.91  61.73  150.76  171.47  18.20
6580       73.12   81.90  ...  289.23  128.55  32.14   78.49   89.27   9.48
6581       73.12   81.90  ...  289.23  128.55  32.14   78.49   89.27   9.48
6582      145.93  160.94  ...  710.48  236.84  78.94  156.64  175.42  18.79
6583       72.71   81.45  ...  287.61  127.82  31.96   78.05   88.78   9.43

                              totalht1
GARANTIE G08ttc GFGttc SINttc
0           5.9   48.0    0.0  2092.43
1           5.9   48.0    0.0  3037.22
2           5.9   48.0    0.0   894.31
3           5.9   48.0    0.0   894.31
4           5.9   48.0    0.0   894.31
...         ...    ...    ...      ...
6579        5.9   48.0    0.0  3146.16
6580        5.9   48.0    0.0  1637.98
6581        5.9   48.0    0.0  1637.98
6582        3.3   48.0    0.0  3221.07
6583        5.9   48.0    0.0  1628.80

[6584 rows x 25 columns]

In [112]:
new_df_pivot_all["totalttc1"] = new_df_pivot_all[("TTC","G01ttc")]+new_df_pivot_all[("TTC","G02ttc")]+new_df_pivot_all[("TTC","G03ttc")] + new_df_pivot_all[("TTC","G04ttc")]+new_df_pivot_all[("TTC","G05ttc")]+new_df_pivot_all[("TTC","G06ttc")] +new_df_pivot_all[("TTC","G07ttc")]+new_df_pivot_all[("TTC","G08ttc")]

In [113]:
new_df_pivot_all

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...     TTC                                       \
GARANTIE   G05ht   G06ht  ...  G03ttc G04ttc  G05ttc  G06ttc G07ttc G08ttc
0          93.41  104.62  ...  164.21  41.05  100.27  114.04  12.11    5.9
1         135.59  151.86  ...  238.36  59.59  145.54  165.53  17.58    5.9
2          39.93   44.72  ...   70.19  17.55   42.86   48.74   5.18    5.9
3          39.93   44.72  ...   70.19  17.55   42.86   48.74   5.18    5.9
4          39.93   44.72  ...   70.19  17.55   42.86   48.74   5.18    5.9
...          ...     ...  ...     ...    ...     ...     ...    ...    ...
6579      140.45  157.31  ...  246.91  61.73  150.76  171.47  18.20    5.9
6580       73.12   81.90  ...  128.55  32.14   78.49   89.27   9.48    5.9
6581       73.12   81.90  ...  128.55  32.14   78.49   89.27   9.48    5.9
6582      145.93  160.94  ...  236.84  78.94  156.64  175.42  18.79    3.3
6583       72.71   81.45  ...  127.82  31.96   78.05   88.78   9.43    5.9

                       totalht1 totalttc1
GARANTIE GFGttc SINttc
0          48.0    0.0  2092.43   2285.00
1          48.0    0.0  3037.22   3314.06
2          48.0    0.0   894.31    980.00
3          48.0    0.0   894.31    980.00
4          48.0    0.0   894.31    980.00
...         ...    ...      ...       ...
6579       48.0    0.0  3146.16   3432.72
6580       48.0    0.0  1637.98   1790.00
6581       48.0    0.0  1637.98   1790.00
6582       48.0    0.0  3221.07   3511.84
6583       48.0    0.0  1628.80   1780.00

[6584 rows x 26 columns]

In [114]:
new_df_pivot_all["DOREV"] = new_df_pivot_all["totalttc1"] - new_df_pivot_all["COM"]
new_df_pivot_all

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...    TTC                                       \
GARANTIE   G05ht   G06ht  ... G04ttc  G05ttc  G06ttc G07ttc G08ttc GFGttc
0          93.41  104.62  ...  41.05  100.27  114.04  12.11    5.9   48.0
1         135.59  151.86  ...  59.59  145.54  165.53  17.58    5.9   48.0
2          39.93   44.72  ...  17.55   42.86   48.74   5.18    5.9   48.0
3          39.93   44.72  ...  17.55   42.86   48.74   5.18    5.9   48.0
4          39.93   44.72  ...  17.55   42.86   48.74   5.18    5.9   48.0
...          ...     ...  ...    ...     ...     ...    ...    ...    ...
6579      140.45  157.31  ...  61.73  150.76  171.47  18.20    5.9   48.0
6580       73.12   81.90  ...  32.14   78.49   89.27   9.48    5.9   48.0
6581       73.12   81.90  ...  32.14   78.49   89.27   9.48    5.9   48.0
6582      145.93  160.94  ...  78.94  156.64  175.42  18.79    3.3   48.0
6583       72.71   81.45  ...  31.96   78.05   88.78   9.43    5.9   48.0

                totalht1 totalttc1    DOREV
GARANTIE SINttc
0           0.0  2092.43   2285.00  2035.63
1           0.0  3037.22   3314.06  2960.77
2           0.0   894.31    980.00   862.43
3           0.0   894.31    980.00   862.43
4           0.0   894.31    980.00   862.43
...         ...      ...       ...      ...
6579        0.0  3146.16   3432.72  3067.44
6580        0.0  1637.98   1790.00  1590.62
6581        0.0  1637.98   1790.00  1590.62
6582        0.0  3221.07   3511.84  3299.38
6583        0.0  1628.80   1780.00  1581.63

[6584 rows x 27 columns]

In [115]:
new_df_pivot_all["DOTAX7"] = new_df_pivot_all[("HT","G05ht")] *(7.34/100)

In [116]:
new_df_pivot_all

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...     TTC                                      \
GARANTIE   G05ht   G06ht  ...  G05ttc  G06ttc G07ttc G08ttc GFGttc SINttc
0          93.41  104.62  ...  100.27  114.04  12.11    5.9   48.0    0.0
1         135.59  151.86  ...  145.54  165.53  17.58    5.9   48.0    0.0
2          39.93   44.72  ...   42.86   48.74   5.18    5.9   48.0    0.0
3          39.93   44.72  ...   42.86   48.74   5.18    5.9   48.0    0.0
4          39.93   44.72  ...   42.86   48.74   5.18    5.9   48.0    0.0
...          ...     ...  ...     ...     ...    ...    ...    ...    ...
6579      140.45  157.31  ...  150.76  171.47  18.20    5.9   48.0    0.0
6580       73.12   81.90  ...   78.49   89.27   9.48    5.9   48.0    0.0
6581       73.12   81.90  ...   78.49   89.27   9.48    5.9   48.0    0.0
6582      145.93  160.94  ...  156.64  175.42  18.79    3.3   48.0    0.0
6583       72.71   81.45  ...   78.05   88.78   9.43    5.9   48.0    0.0

         totalht1 totalttc1    DOREV     DOTAX7
GARANTIE
0         2092.43   2285.00  2035.63   6.856294
1         3037.22   3314.06  2960.77   9.952306
2          894.31    980.00   862.43   2.930862
3          894.31    980.00   862.43   2.930862
4          894.31    980.00   862.43   2.930862
...           ...       ...      ...        ...
6579      3146.16   3432.72  3067.44  10.309030
6580      1637.98   1790.00  1590.62   5.367008
6581      1637.98   1790.00  1590.62   5.367008
6582      3221.07   3511.84  3299.38  10.711262
6583      1628.80   1780.00  1581.63   5.336914

[6584 rows x 28 columns]

In [117]:
new_df_pivot_all["DOTAX8"] = 0

In [118]:
new_df_pivot_all["DOTAX9"] = new_df_pivot_all[("totalht1")] *(9.00/100)

In [119]:
new_df_pivot_all

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
0          10778  2  249.37          439.41  1355.91  338.97  150.65  37.66
1          10778  3  353.29          637.82  1968.12  492.03  218.68  54.67
2          10778  4  117.57          187.80   579.50  144.88   64.39  16.10
3          10778  5  117.57          187.80   579.50  144.88   64.39  16.10
4          10778  6  117.57          187.80   579.50  144.88   64.39  16.10
...          ... ..     ...             ...      ...     ...     ...    ...
6579        8753  7  365.28          660.69  2038.71  509.69  226.52  56.63
6580        8753  8  199.38          343.98  1061.41  265.35  117.94  29.49
6581        8753  9  199.38          343.98  1061.41  265.35  117.94  29.49
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42
6583        9191  1  198.37          342.05  1055.46  263.86  117.27  29.32

                          ...    TTC                      totalht1 totalttc1  \
GARANTIE   G05ht   G06ht  ... G07ttc G08ttc GFGttc SINttc
0          93.41  104.62  ...  12.11    5.9   48.0    0.0  2092.43   2285.00
1         135.59  151.86  ...  17.58    5.9   48.0    0.0  3037.22   3314.06
2          39.93   44.72  ...   5.18    5.9   48.0    0.0   894.31    980.00
3          39.93   44.72  ...   5.18    5.9   48.0    0.0   894.31    980.00
4          39.93   44.72  ...   5.18    5.9   48.0    0.0   894.31    980.00
...          ...     ...  ...    ...    ...    ...    ...      ...       ...
6579      140.45  157.31  ...  18.20    5.9   48.0    0.0  3146.16   3432.72
6580       73.12   81.90  ...   9.48    5.9   48.0    0.0  1637.98   1790.00
6581       73.12   81.90  ...   9.48    5.9   48.0    0.0  1637.98   1790.00
6582      145.93  160.94  ...  18.79    3.3   48.0    0.0  3221.07   3511.84
6583       72.71   81.45  ...   9.43    5.9   48.0    0.0  1628.80   1780.00

            DOREV     DOTAX7 DOTAX8    DOTAX9
GARANTIE
0         2035.63   6.856294      0  188.3187
1         2960.77   9.952306      0  273.3498
2          862.43   2.930862      0   80.4879
3          862.43   2.930862      0   80.4879
4          862.43   2.930862      0   80.4879
...           ...        ...    ...       ...
6579      3067.44  10.309030      0  283.1544
6580      1590.62   5.367008      0  147.4182
6581      1590.62   5.367008      0  147.4182
6582      3299.38  10.711262      0  289.8963
6583      1581.63   5.336914      0  146.5920

[6584 rows x 30 columns]

In [120]:
new_df_pivot_all[(new_df_pivot_all["CONTRAT"]=='8868') & (new_df_pivot_all["NC"]=='1')]

         CONTRAT NC     COM ligq_commission       HT                         \
GARANTIE                                       G01ht   G02ht   G03ht  G04ht
6582        8868  1  212.46          418.74  1955.44  651.82  217.28  72.42

                          ...    TTC                      totalht1 totalttc1  \
GARANTIE   G05ht   G06ht  ... G07ttc G08ttc GFGttc SINttc
6582      145.93  160.94  ...  18.79    3.3   48.0    0.0  3221.07   3511.84

            DOREV     DOTAX7 DOTAX8    DOTAX9
GARANTIE
6582      3299.38  10.711262      0  289.8963

[1 rows x 30 columns]

In [121]:
df

,f_NCONTRAT,CONTRAT,NC,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,AGENCE_A2,AGENCE_CP,AGENCE_VILLE,...,PRIMEG,TTCG,COM,ligq_commission,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,1355.91,1477.94,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,338.97,369.48,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
2,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,150.65,164.21,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
3,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,37.66,41.05,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
4,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,93.41,100.27,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59937,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,72.71,78.05,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59938,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,81.45,88.78,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59939,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,8.73,9.43,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59940,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,5.90,5.90,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59941,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,48.00,48.00,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [122]:
#ajout autre champ lambda
df.columns

Index(['f_NCONTRAT', 'CONTRAT', 'NC', 'REF_CGAIM', 'LCGAIM', 'AGENCE',
       'AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1',
       'CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',
       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2',
       'COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8',
       'COUTTX9', 'GARANTIE', 'GARANTIEG', 'FRAIS', 'PRIME', 'HT', 'TTC',
       'PRIMEG', 'TTCG', 'COM', 'ligq_commission', 'DTSITUATION', 'DOMAGIS_ON',
       'DTRECOUVREMENT', 'MOUVEMENT', 'STATUT', 'TXCOM'],
      dtype='object')

In [127]:
df_info1 = df[['f_NCONTRAT', 'CONTRAT', 'NC', 'REF_CGAIM', 'LCGAIM', 'AGENCE','AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1','CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',
       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2','COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8','COUTTX9', 'COM', 'ligq_commission', 'DTSITUATION', 'DOMAGIS_ON','DTRECOUVREMENT',
               'MOUVEMENT', 'STATUT', 'TXCOM']];df_info1

,f_NCONTRAT,CONTRAT,NC,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,AGENCE_A2,AGENCE_CP,AGENCE_VILLE,...,COUTTX8,COUTTX9,COM,ligq_commission,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
2,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
3,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
4,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59937,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59938,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59939,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59940,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59941,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [130]:
df_info1.columns

Index(['f_NCONTRAT', 'CONTRAT', 'NC', 'REF_CGAIM', 'LCGAIM', 'AGENCE',
       'AGENCE_A1', 'AGENCE_A2', 'AGENCE_CP', 'AGENCE_VILLE', 'CHANTIER1',
       'CHANTIER2', 'CHANTIER3', 'CPCHANTIER', 'VILLECHANT', 'Debut', 'Fin',
       'NATURE1', 'NATURE2', 'NATURE3', 'COUTTX', 'COUTTX1', 'COUTTX2',
       'COUTTX3', 'COUTTX4', 'COUTTX5', 'COUTTX6', 'COUTTX7', 'COUTTX8',
       'COUTTX9', 'COM', 'ligq_commission', 'DTSITUATION', 'DOMAGIS_ON',
       'DTRECOUVREMENT', 'MOUVEMENT', 'STATUT', 'TXCOM'],
      dtype='object')

In [131]:
df_info2 = df_info1.drop_duplicates()

In [134]:
df_info2.reset_index()

,index,f_NCONTRAT,CONTRAT,NC,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,AGENCE_A2,AGENCE_CP,...,COUTTX8,COUTTX9,COM,ligq_commission,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,0,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,...,0.0,0.0,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10,10778/3,10778,3,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,...,0.0,0.0,353.29,637.82,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,20,10778/4,10778,4,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,...,0.0,0.0,117.57,187.80,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,29,10778/5,10778,5,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,...,0.0,0.0,117.57,187.80,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,38,10778/6,10778,6,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,...,0.0,0.0,117.57,187.80,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,59894,8753/7,8753,7,25 772,25 772,BILAN PATRIMOINE,Résidence l' Alcyone,23 avenue Roger Salengro,34170,...,0.0,0.0,365.28,660.69,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,59904,8753/8,8753,8,25 772,25 772,BILAN PATRIMOINE,Résidence l' Alcyone,23 avenue Roger Salengro,34170,...,0.0,0.0,199.38,343.98,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,59914,8753/9,8753,9,25 772,25 772,BILAN PATRIMOINE,Résidence l' Alcyone,23 avenue Roger Salengro,34170,...,0.0,0.0,199.38,343.98,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,59924,8868/1,8868,1,100482,100482,A G ENCE STRASBOURG IMMOBILIERE,Le Mathis,200 avenue de Colmar,67025,...,0.0,0.0,212.46,418.74,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,59933,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,...,0.0,0.0,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [135]:
new_df_pivot_all2 = new_df_pivot_all.merge( df_info2, on=['CONTRAT', 'NC',  'COM', 'ligq_commission']);new_df_pivot_all2

D:\anaconda\lib\site-packages\pandas\core\reshape\merge.py:618: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)

,CONTRAT,NC,COM,ligq_commission,"(CONTRAT, )","(NC, )","(COM, )","(ligq_commission, )","(HT, G01ht)","(HT, G02ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778,2,249.37,439.41,10778,2,249.37,439.41,1355.91,338.97,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778,3,353.29,637.82,10778,3,353.29,637.82,1968.12,492.03,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,10778,4,117.57,187.80,10778,4,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,10778,5,117.57,187.80,10778,5,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,10778,6,117.57,187.80,10778,6,117.57,187.80,579.50,144.88,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,8753,7,365.28,660.69,8753,7,365.28,660.69,2038.71,509.69,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,8753,8,199.38,343.98,8753,8,199.38,343.98,1061.41,265.35,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,8753,9,199.38,343.98,8753,9,199.38,343.98,1061.41,265.35,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,8868,1,212.46,418.74,8868,1,212.46,418.74,1955.44,651.82,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,9191,1,198.37,342.05,9191,1,198.37,342.05,1055.46,263.86,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [136]:
new_df_pivot_all2.columns

Index([              'CONTRAT',                    'NC',
                         'COM',       'ligq_commission',
               ('CONTRAT', ''),              ('NC', ''),
                   ('COM', ''), ('ligq_commission', ''),
               ('HT', 'G01ht'),         ('HT', 'G02ht'),
               ('HT', 'G03ht'),         ('HT', 'G04ht'),
               ('HT', 'G05ht'),         ('HT', 'G06ht'),
               ('HT', 'G07ht'),         ('HT', 'G08ht'),
               ('HT', 'GFGht'),         ('HT', 'SINht'),
             ('TTC', 'G01ttc'),       ('TTC', 'G02ttc'),
             ('TTC', 'G03ttc'),       ('TTC', 'G04ttc'),
             ('TTC', 'G05ttc'),       ('TTC', 'G06ttc'),
             ('TTC', 'G07ttc'),       ('TTC', 'G08ttc'),
             ('TTC', 'GFGttc'),       ('TTC', 'SINttc'),
              ('totalht1', ''),       ('totalttc1', ''),
                 ('DOREV', ''),          ('DOTAX7', ''),
                ('DOTAX8', ''),          ('DOTAX9', ''),
                  'f_NCONTRAT',             'REF_CGAIM',
                      'LCGAIM',                'AGENCE',
                   'AGENCE_A1',             'AGENCE_A2',
                   'AGENCE_CP',          'AGENCE_VILLE',
                   'CHANTIER1',             'CHANTIER2',
                   'CHANTIER3',            'CPCHANTIER',
                  'VILLECHANT',                 'Debut',
                         'Fin',               'NATURE1',
                     'NATURE2',               'NATURE3',
                      'COUTTX',               'COUTTX1',
                     'COUTTX2',               'COUTTX3',
                     'COUTTX4',               'COUTTX5',
                     'COUTTX6',               'COUTTX7',
                     'COUTTX8',               'COUTTX9',
                 'DTSITUATION',            'DOMAGIS_ON',
              'DTRECOUVREMENT',             'MOUVEMENT',
                      'STATUT',                 'TXCOM'],
      dtype='object')

In [137]:
df

,f_NCONTRAT,CONTRAT,NC,REF_CGAIM,LCGAIM,AGENCE,AGENCE_A1,AGENCE_A2,AGENCE_CP,AGENCE_VILLE,...,PRIMEG,TTCG,COM,ligq_commission,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,1355.91,1477.94,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,338.97,369.48,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
2,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,150.65,164.21,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
3,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,37.66,41.05,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
4,10778/2,10778,2,27039,27039,AGENCE DU CAP,Avenue de la Jetée,,34300,CAP D'AGDE,...,93.41,100.27,249.37,439.41,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59937,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,72.71,78.05,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59938,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,81.45,88.78,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59939,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,8.73,9.43,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59940,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,5.90,5.90,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0
59941,9191/1,9191,1,None,None,IMMOBILIERE LORI,26 avenue Gabriel Péri,,91700,STE-GENEVIEVE-DES-BOIS,...,48.00,48.00,198.37,342.05,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [138]:
new_df_pivot_all2.reset_index()

,index,CONTRAT,NC,COM,ligq_commission,"(CONTRAT, )","(NC, )","(COM, )","(ligq_commission, )","(HT, G01ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,0,10778,2,249.37,439.41,10778,2,249.37,439.41,1355.91,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,1,10778,3,353.29,637.82,10778,3,353.29,637.82,1968.12,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,2,10778,4,117.57,187.80,10778,4,117.57,187.80,579.50,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,3,10778,5,117.57,187.80,10778,5,117.57,187.80,579.50,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,4,10778,6,117.57,187.80,10778,6,117.57,187.80,579.50,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,6587,8753,7,365.28,660.69,8753,7,365.28,660.69,2038.71,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,6588,8753,8,199.38,343.98,8753,8,199.38,343.98,1061.41,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,6589,8753,9,199.38,343.98,8753,9,199.38,343.98,1061.41,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,6590,8868,1,212.46,418.74,8868,1,212.46,418.74,1955.44,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,6591,9191,1,198.37,342.05,9191,1,198.37,342.05,1055.46,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [144]:
new_df_pivot_all2.columns

Index([              'CONTRAT',                    'NC',
                         'COM',       'ligq_commission',
               ('CONTRAT', ''),              ('NC', ''),
                   ('COM', ''), ('ligq_commission', ''),
               ('HT', 'G01ht'),         ('HT', 'G02ht'),
               ('HT', 'G03ht'),         ('HT', 'G04ht'),
               ('HT', 'G05ht'),         ('HT', 'G06ht'),
               ('HT', 'G07ht'),         ('HT', 'G08ht'),
               ('HT', 'GFGht'),         ('HT', 'SINht'),
             ('TTC', 'G01ttc'),       ('TTC', 'G02ttc'),
             ('TTC', 'G03ttc'),       ('TTC', 'G04ttc'),
             ('TTC', 'G05ttc'),       ('TTC', 'G06ttc'),
             ('TTC', 'G07ttc'),       ('TTC', 'G08ttc'),
             ('TTC', 'GFGttc'),       ('TTC', 'SINttc'),
              ('totalht1', ''),       ('totalttc1', ''),
                 ('DOREV', ''),          ('DOTAX7', ''),
                ('DOTAX8', ''),          ('DOTAX9', ''),
                  'f_NCONTRAT',             'REF_CGAIM',
                      'LCGAIM',                'AGENCE',
                   'AGENCE_A1',             'AGENCE_A2',
                   'AGENCE_CP',          'AGENCE_VILLE',
                   'CHANTIER1',             'CHANTIER2',
                   'CHANTIER3',            'CPCHANTIER',
                  'VILLECHANT',                 'Debut',
                         'Fin',               'NATURE1',
                     'NATURE2',               'NATURE3',
                      'COUTTX',               'COUTTX1',
                     'COUTTX2',               'COUTTX3',
                     'COUTTX4',               'COUTTX5',
                     'COUTTX6',               'COUTTX7',
                     'COUTTX8',               'COUTTX9',
                 'DTSITUATION',            'DOMAGIS_ON',
              'DTRECOUVREMENT',             'MOUVEMENT',
                      'STATUT',                 'TXCOM'],
      dtype='object')

In [157]:
new_df_pivot_all2.loc[4,['CONTRAT','NC',('CONTRAT', '')]]

CONTRAT        10778
NC                 6
(CONTRAT, )    10778
Name: 4, dtype: object

In [164]:
new_df_pivot_all2.drop(columns=[('CONTRAT', '')],inplace=True);

KeyError: "[('CONTRAT', '')] not found in axis"

In [173]:
new_df_pivot_all2

,CONTRAT,NC,COM,ligq_commission,"(HT, G01ht)","(HT, G02ht)","(HT, G03ht)","(HT, G04ht)","(HT, G05ht)","(HT, G06ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778,2,249.37,439.41,1355.91,338.97,150.65,37.66,93.41,104.62,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778,3,353.29,637.82,1968.12,492.03,218.68,54.67,135.59,151.86,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,10778,4,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,10778,5,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,10778,6,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,8753,7,365.28,660.69,2038.71,509.69,226.52,56.63,140.45,157.31,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,8753,8,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,8753,9,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,8868,1,212.46,418.74,1955.44,651.82,217.28,72.42,145.93,160.94,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,9191,1,198.37,342.05,1055.46,263.86,117.27,29.32,72.71,81.45,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [168]:
new_df_pivot_all2.drop(columns=[('NC', '')],inplace=True);

In [170]:
new_df_pivot_all2.drop(columns=[('COM', '')],inplace=True);

In [172]:
new_df_pivot_all2.drop(columns=[('ligq_commission', '')],inplace=True);

In [174]:
new_df_pivot_all2.columns

Index([        'CONTRAT',              'NC',             'COM',
       'ligq_commission',   ('HT', 'G01ht'),   ('HT', 'G02ht'),
         ('HT', 'G03ht'),   ('HT', 'G04ht'),   ('HT', 'G05ht'),
         ('HT', 'G06ht'),   ('HT', 'G07ht'),   ('HT', 'G08ht'),
         ('HT', 'GFGht'),   ('HT', 'SINht'), ('TTC', 'G01ttc'),
       ('TTC', 'G02ttc'), ('TTC', 'G03ttc'), ('TTC', 'G04ttc'),
       ('TTC', 'G05ttc'), ('TTC', 'G06ttc'), ('TTC', 'G07ttc'),
       ('TTC', 'G08ttc'), ('TTC', 'GFGttc'), ('TTC', 'SINttc'),
        ('totalht1', ''), ('totalttc1', ''),     ('DOREV', ''),
          ('DOTAX7', ''),    ('DOTAX8', ''),    ('DOTAX9', ''),
            'f_NCONTRAT',       'REF_CGAIM',          'LCGAIM',
                'AGENCE',       'AGENCE_A1',       'AGENCE_A2',
             'AGENCE_CP',    'AGENCE_VILLE',       'CHANTIER1',
             'CHANTIER2',       'CHANTIER3',      'CPCHANTIER',
            'VILLECHANT',           'Debut',             'Fin',
               'NATURE1',         'NATURE2',         'NATURE3',
                'COUTTX',         'COUTTX1',         'COUTTX2',
               'COUTTX3',         'COUTTX4',         'COUTTX5',
               'COUTTX6',         'COUTTX7',         'COUTTX8',
               'COUTTX9',     'DTSITUATION',      'DOMAGIS_ON',
        'DTRECOUVREMENT',       'MOUVEMENT',          'STATUT',
                 'TXCOM'],
      dtype='object')

In [175]:
new_df_pivot_all2

,CONTRAT,NC,COM,ligq_commission,"(HT, G01ht)","(HT, G02ht)","(HT, G03ht)","(HT, G04ht)","(HT, G05ht)","(HT, G06ht)",...,COUTTX6,COUTTX7,COUTTX8,COUTTX9,DTSITUATION,DOMAGIS_ON,DTRECOUVREMENT,MOUVEMENT,STATUT,TXCOM
0,10778,2,249.37,439.41,1355.91,338.97,150.65,37.66,93.41,104.62,...,0.0,0.0,0.0,0.0,2016-10-01,DOMAGIS,2017-03-08 00:00:00.000,44,Modification,11.0
1,10778,3,353.29,637.82,1968.12,492.03,218.68,54.67,135.59,151.86,...,0.0,0.0,0.0,0.0,2018-09-24,DOMAGIS,2018-09-20 13:53:13.907,44,Modification,11.0
2,10778,4,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2019-11-04,DOMAGIS,2019-08-27 15:45:35.993,39,Ajout,11.0
3,10778,5,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2020-04-21,DOMAGIS,2020-06-18 10:37:43.997,44,Modification,11.0
4,10778,6,117.57,187.80,579.50,144.88,64.39,16.10,39.93,44.72,...,0.0,0.0,0.0,0.0,2021-01-18,DOMAGIS,2021-01-08 09:18:56.730,44,Modification,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6587,8753,7,365.28,660.69,2038.71,509.69,226.52,56.63,140.45,157.31,...,0.0,0.0,0.0,0.0,2017-03-01,DOMAGIS,2017-06-08 00:00:00.000,44,Modification,11.0
6588,8753,8,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-09-01,DOMAGIS,2017-07-31 00:00:00.000,44,Modification,11.0
6589,8753,9,199.38,343.98,1061.41,265.35,117.94,29.49,73.12,81.90,...,0.0,0.0,0.0,0.0,2017-11-15,DOMAGIS,2017-09-29 10:08:03.610,44,Modification,11.0
6590,8868,1,212.46,418.74,1955.44,651.82,217.28,72.42,145.93,160.94,...,0.0,0.0,0.0,0.0,2015-10-01,DOMAGIS,2015-10-20 00:00:00.000,1,Ajout,6.0
6591,9191,1,198.37,342.05,1055.46,263.86,117.27,29.32,72.71,81.45,...,0.0,0.0,0.0,0.0,2021-05-08,DOMAGIS,2022-03-23 13:58:14.380,44,Modification,11.0

In [176]:
new_df_pivot_all2.columns

Index([        'CONTRAT',              'NC',             'COM',
       'ligq_commission',   ('HT', 'G01ht'),   ('HT', 'G02ht'),
         ('HT', 'G03ht'),   ('HT', 'G04ht'),   ('HT', 'G05ht'),
         ('HT', 'G06ht'),   ('HT', 'G07ht'),   ('HT', 'G08ht'),
         ('HT', 'GFGht'),   ('HT', 'SINht'), ('TTC', 'G01ttc'),
       ('TTC', 'G02ttc'), ('TTC', 'G03ttc'), ('TTC', 'G04ttc'),
       ('TTC', 'G05ttc'), ('TTC', 'G06ttc'), ('TTC', 'G07ttc'),
       ('TTC', 'G08ttc'), ('TTC', 'GFGttc'), ('TTC', 'SINttc'),
        ('totalht1', ''), ('totalttc1', ''),     ('DOREV', ''),
          ('DOTAX7', ''),    ('DOTAX8', ''),    ('DOTAX9', ''),
            'f_NCONTRAT',       'REF_CGAIM',          'LCGAIM',
                'AGENCE',       'AGENCE_A1',       'AGENCE_A2',
             'AGENCE_CP',    'AGENCE_VILLE',       'CHANTIER1',
             'CHANTIER2',       'CHANTIER3',      'CPCHANTIER',
            'VILLECHANT',           'Debut',             'Fin',
               'NATURE1',         'NATURE2',         'NATURE3',
                'COUTTX',         'COUTTX1',         'COUTTX2',
               'COUTTX3',         'COUTTX4',         'COUTTX5',
               'COUTTX6',         'COUTTX7',         'COUTTX8',
               'COUTTX9',     'DTSITUATION',      'DOMAGIS_ON',
        'DTRECOUVREMENT',       'MOUVEMENT',          'STATUT',
                 'TXCOM'],
      dtype='object')

In [180]:
new_df_pivot_all2[('HT','G03ht')]

0       150.65
1       218.68
2        64.39
3        64.39
4        64.39
         ...
6587    226.52
6588    117.94
6589    117.94
6590    217.28
6591    117.27
Name: (HT, G03ht), Length: 6592, dtype: float64

In [181]:
new_df_pivot_all2[('HT','G03ht')][6587]

226.52

In [182]:
m1 = new_df_pivot_all2[('HT','G03ht')][6587]

In [183]:
m1

226.52

In [1]:
new_df_pivot_all[(new_df_pivot_all["CONTRAT"]=='8868') & (new_df_pivot_all["NC"]=='1')]

NameError: name 'new_df_pivot_all' is not defined